### ISSUE TITLE
Support Graphs For Specific Branches

### ISSUE THREAD

**Issue by martincostello** [dustinmoris/CI-BuildStats#1]
I've been experimenting with the gadget on a number of existing builds with AppVeyor and Travis CI, and it appears that builds from all branches are considered, including builds related to Pull Requests.

Would it be possible to add a query string parameter (or a route parameter) that allows the branch to be specified, for example:

```
https://ci-buildstats.azurewebsites.net/{buildSystem}/chart/{account}/{project}/{branch}
```

Similar badge providers have the same functionality.

**Comment by dustinmoris** [comment]
That makes sense and I didn't even think of this when I did the initial release. Will add it tonight! Thanks!

**Comment by 304NotModified** [comment]
+1

**Comment by dustinmoris** [comment]
You can specify the branch via a query string parameter now:
https://ci-buildstats.azurewebsites.net/{buildSystem}/chart/{account}/{project}?branch={branch}

Thanks for bringing this up!

**Comment by martincostello** [comment]
@dustinmoris Thanks for the quick fix Dustin, most appreciated. However, builds from PRs are still included, presumably because they are PRs to the master branch in my case.

In the case of Travis CI, these can be distinguished by the build having the following properties in the JSON: ```"event_type":"pull_request"``` (instead of ```"event_type":"push"```). For AppVeyor, the builds have a ```pullRequestId``` property that is otherwise absent.

Would it be possible to support excluding PR builds as well? If so, would you rather than be opened as a separate issue?

**Comment by dustinmoris** [comment]
Thanks for the clarification. I reopened the issue and I will try to get this done tonight !

**Comment by martincostello** [comment]
@dustinmoris Thanks a lot :)

**Comment by dustinmoris** [comment]
I added the following parameter: includeBuildsFromPullRequest={true/false}
(true by default)
Hope this works for you now :)

**Comment by martincostello** [comment]
Just tried this out, I think there's just one last thing.

In the case of AppVeyor, it appears that the filtering happens after the number of builds is taken into account, meaning that you don't get the full 25 builds by default. For Travis CI it seems to work as I'd expect. The URLs I'm using to test this are below:

  * [AppVeyor 1](https://ci-buildstats.azurewebsites.net/appveyor/chart/martincostello/sqllocaldb?branch=master&includeBuildsFromPullRequest=false)
  * [AppVeyor 2](https://ci-buildstats.azurewebsites.net/travisci/chart/experiandataquality/electronicupdates?branch=master&includeBuildsFromPullRequest=false)
  * [Travis CI](https://ci-buildstats.azurewebsites.net/appveyor/chart/experiandataquality/electronicupdates?branch=master&includeBuildsFromPullRequest=false)

**Comment by dustinmoris** [comment]
Sorry for the late reply. I was a bit busy the last couple days but got around to fix it today!

**Comment by martincostello** [comment]
Thanks very much! I'll do a more detailed look on my computer a bit later this morning to double check, but from what I can see on my phone looks good.

**Comment by martincostello** [comment]
@dustinmoris LGTM :+1:

**Comment by martincostello** [comment]
@dustinmoris Integrated into repos, thanks again.

[martincostello/sqllocaldb](https://github.com/martincostello/sqllocaldb)
[experiandataquality/electronicupdates](https://github.com/experiandataquality/electronicupdates)

**Comment by dustinmoris** [comment]
Great stuff, glad you like it! :)
