### ISSUE TITLE
TravisCI canceled jobs display as red

### ISSUE THREAD

**Issue by Fryguy** [dustinmoris/CI-BuildStats#11]
Would it be possible to show them as grey instead?  I noticed some of the other parsers have a cancelled status, but TravisCI does not (See [here](https://github.com/dustinmoris/CI-BuildStats/blob/master/BuildStats.Core/BuildHistoryChart/TravisCI/TravisCIBuildHistoryParser.cs#L41-L43)).  I tried changing it myself, but I don't see a cancelled status in the API callback, which is perhaps the real issue.  However, the ruby gem somehow returns a cancelled status and I can't understand yet where that's coming from.  I know Travis has an "old" API and a "new" API, so perhaps that's part of the issue.

**Comment by dustinmoris** [comment]
Sure, would you mind telling me the account/repo name where you see this issue. I will see if I can fix it later tonight.

**Comment by dustinmoris** [comment]
I tested it with my own build history: https://buildstats.info/travisci/chart/dustinmoris/CI-BuildStats

Thanks for reporting this bug!

**Comment by jrafanie** [comment]
Thanks @dustinmoris, it looks much better now:
https://github.com/ManageIQ/manageiq


![image](https://cloud.githubusercontent.com/assets/19339/15454776/d56fb0f2-200f-11e6-9e40-0293e7678579.png)

**Comment by Fryguy** [comment]
Thanks @dustinmoris!  Looks great!
