### ISSUE TITLE
Prerelease NuGet packages included by default

### ISSUE THREAD

**Issue by martincostello** [dustinmoris/CI-BuildStats#14]
The documentation suggests that prerelease versions for the NuGet badge are opt-in, but the service does not appear to be behaving in this way. Is this a regression from the rewrite into F#?

**Expected behaviour**

| **URL** | **Image** |
| :--: | :--: |
| ```https://buildstats.info/nuget/JustEat.StatsD``` | [![NuGet version](https://buildstats.info/nuget/JustEat.StatsD?includePreReleases=false)](http://www.nuget.org/packages/JustEat.StatsD) |
| ```https://buildstats.info/nuget/JustEat.StatsD?includePreReleases=false``` | [![NuGet version](https://buildstats.info/nuget/JustEat.StatsD?includePreReleases=false)](http://www.nuget.org/packages/JustEat.StatsD) |
| ```https://buildstats.info/nuget/JustEat.StatsD?includePreReleases=true``` | [![NuGet version](https://buildstats.info/nuget/JustEat.StatsD?includePreReleases=true)](http://www.nuget.org/packages/JustEat.StatsD) |

**Actual behaviour**

| **URL** | **Image** |
| :--: | :--: |
| ```https://buildstats.info/nuget/JustEat.StatsD``` | [![NuGet version](https://buildstats.info/nuget/JustEat.StatsD)](http://www.nuget.org/packages/JustEat.StatsD) |
| ```https://buildstats.info/nuget/JustEat.StatsD?includePreReleases=false``` | [![NuGet version](https://buildstats.info/nuget/JustEat.StatsD?includePreReleases=false)](http://www.nuget.org/packages/JustEat.StatsD) |
| ```https://buildstats.info/nuget/JustEat.StatsD?includePreReleases=true``` | [![NuGet version](https://buildstats.info/nuget/JustEat.StatsD?includePreReleases=true)](http://www.nuget.org/packages/JustEat.StatsD) |

_Note: The expected behaviour badges use a different URL that that listed in the table next to them so that the image is rendered correctly for illustrating the issue._

**Comment by dustinmoris** [comment]
Hi, sorry for the late reply. It could be a regression issue. I'd have to test it but I am currently away in a place where I have barely internet and no laptop either. If this is an issue that you'd like to have fixed quickly then you could send me a PR with the fix and I could merge it, otherwise I can pick it up on the 21st Nov again.

**Comment by martincostello** [comment]
No problem, it's not urgent. I've just worked around it by explicitly adding the query string.

**Comment by dustinmoris** [comment]
Deployment finished and I can see that the expected and actual behaviour match now. Thank you again for reporting this issue!
