### ISSUE TITLE
Support travis-ci.com

### ISSUE THREAD

**Issue by martincostello** [dustinmoris/CI-BuildStats#17]
New repositories/accounts created with Travis CI may now be created at `travis-ci.com` instead of `travis-ci.org` as part of Travis' infrastructure migration.

As the API URL is hard-coded at present, it is not possible to generate charts for builds in `travis-ci.com`.

https://github.com/dustinmoris/CI-BuildStats/blob/d275648710c6b93fa6543c95b3099849ae63f072/src/BuildStats/BuildHistoryCharts.fs#L196

Two possible approaches to support this could be either:
  1. Adding a query-string parameter to specify that the `.com` version should be used (`?v=2` ?).
  1. Adding a new provider (`travisci2` ?).

**Comment by martincostello** [comment]
I’ll double check tomorrow morning for projects, but accounts can be. My existing projects are all still .org but I created a new one and it got set up as .com which was how I noticed this issue.

I noticed that shields.io supports both by having two different path options, which was where the “toggle” suggestion came from.

I wasn’t sure what the infrastructure impact to you would be by doing a try one then try the other approach.

**Comment by dustinmoris** [comment]
Ok so from reading the [official blog post](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps) it's pretty clear that the days for `travis-ci.org` are counted. Looks like they are going to migrate everything over to `travis-ci.com` and starting with all new projects being created there now.

>New Travis CI Users
Welcome to Travis CI! Go ahead and sign up at travis-ci.com. You will be able to use the GitHub Apps Integration right away, and all of your repositories will be in one place. This is the best time to get started!

>Current Travis CI Users
You can continue to use both your travis-ci.org and travis-ci.com accounts as usual for now. Over the next several months, we’ll be migrating all travis-ci.org repositories and customers to travis-ci.com. Though this will not happen right away, you can go ahead and read more about what to expect in the docs.

With that information I think the best for me to do is to check if a repo returns 200 on travis-ci.com and if it does then don't even bother to go to travis-ci.org. If it doesn't then I'll use `.org` as the fallback and over time the amount of second requests being made to `.org` should go down at which point I'll probably be able to entirely delete that code.

I personally think this is a better option than asking all users now to distinguish between `travisci` and `travisci2` if this is a temporary state anyway.

**Comment by martincostello** [comment]
I think that’s fine then :+1

**Comment by dustinmoris** [comment]
I have deployed a fix today. I updated the code to work against the V3 API of Travis (which is much better btw) and managed to query public repo data from the .com domain with a fallback to .org without the need for an auth token after all.  Even though I didn't need the auth token in the end I have still implemented a first version for private repository support. This is currently in testing and not officially released yet, but if you want to have a dig at it you should be able to encrypt your token [here](https://buildstats.info/create) and then pass in the encrypted value to the Travis endpoint via the `authToken={encrypted value}` query parameter.

Thanks for your help again!

**Comment by martincostello** [comment]
Awesome thanks @dustinmoris. I'll check this out later today 👍

**Comment by martincostello** [comment]
Awesome, it _just worked_ ✨ 

I didn't try the token stuff, but I had a quick peek at the page and FYI there's a 404 in the browser console because it's trying to find a favicon.

**Comment by dustinmoris** [comment]
Hmm weird, I don't have a [reference to any favicon](https://github.com/dustinmoris/CI-BuildStats/search?q=favicon&unscoped_q=favicon) in my entire code base. In my chrome dev tools I also don't get a 404:

![image](https://user-images.githubusercontent.com/4580714/44877691-a4873480-ac9c-11e8-8948-6d8753da8c22.png)

Where did you see this happening?

**Comment by martincostello** [comment]
Ah, maybe it was just the browser being presumptive and trying anyway on the first visit.

**Comment by martincostello** [comment]
I think this may have caused a regression. For an existing project that hasn't been migrated yet, I'm getting an empty graph instead of it falling back to .org.

https://github.com/martincostello/website#martin-costellos-website

**Comment by dustinmoris** [comment]
Hmm weird, I do have tests with non migrated projects and they all work. I'll check this a bit later today!
