### ISSUE TITLE
Support for Enterprise MyGet tenants?

### ISSUE THREAD

**Issue by cleemullins** [dustinmoris/CI-BuildStats#19]
We're using an [Enterprise MyGet tenent](https://botbuilder.myget.org/) for publishing our daily builds. 

Within that tenant, we've got feeds, such as our [daily build feed](https://botbuilder.myget.org/gallery/botbuilder-v4-dotnet-daily). 

I would love to be able to use your tooling to have links to these packages. The code in [PackageServices.fs](https://github.com/dustinmoris/CI-BuildStats/blob/87815f60781591d23a41fc71916b2cfa42df90c9/src/BuildStats/PackageServices.fs) looks like it needs a MyGet Enterprise module with a slightly different API - as it would need to take slightly different parameters as the DNS name differs between tenants. 

I would be happy to personally donate $20 or $50 to have this working. I don't think I have time to submit a PR... (my life is busy in bot-land!)

**Comment by dustinmoris** [comment]
Hi @cleemullins,

> The only difference I see from your current myget code to the revised code is the different URL, which would need to be taken as a parameter

Thanks for looking into the details, sounds fairly easy then.

> I would be happy to personally donate $20 or $50 to have this working.

Much appreciated, but please be assured that I'd love to implement this feature for no other reward than satisfying my own geekiness ;)

> Essentially, I'm trying to build this chart, with the links to the daily builds for the folks that want them

Awesome, thanks for providing the links to your Enterprise MyGet feed and the concrete examples that you would like to create the badge for. With that info I think I should be able to get a working version over the weekend. I'll keep you updated how I get along!

**Comment by dustinmoris** [comment]
Heya,

This was actually such a minor change that I managed to get it implemented, tested and deployed on my 30 min train journey ^^

You should be able to use the following URL now to render an SVG for a MyGet Enterprise package:
```
https://buildstats.info/myget/botbuilder/botbuilder-v4-dotnet-daily/Microsoft.Bot.Builder
```

I have updated the docs in the README for further reference.

Hope this is what you needed!

BTW - the knowledge that you guys are using this is REALLY rewarding enough, so please don't be silly ;)
