### ISSUE TITLE
Yellow page of death when wrong name

### ISSUE THREAD

**Issue by 304NotModified** [dustinmoris/CI-BuildStats#2]
A wrong name in the URL gives a 500 / Yellow page of death. 

https://ci-buildstats.azurewebsites.net/appveyor/chart/a/b

![image](https://cloud.githubusercontent.com/assets/5808377/9603516/6862baf0-50b1-11e5-9a0a-1edca271b023.png)

**Comment by dustinmoris** [comment]
Thanks, will fix this issue later tonight!

**Comment by dustinmoris** [comment]
Fixed. Thanks for raising it!
