### ISSUE TITLE
Consider Fixed Width badges

### ISSUE THREAD

**Issue by cleemullins** [dustinmoris/CI-BuildStats#22]
As the download counts of packages get wider, it causes overall width to change. This makes tables of these look jagged. 

Consider a "Fixed width" or a "Padded Width" or "Normalize To" as an option. 

![image](https://user-images.githubusercontent.com/1165321/46899515-36ac5c00-ce49-11e8-865a-011b2c61af39.png)

An easy answer may simply be parameters for width for 2 two variable fields:
```
downloadCountWidth=500px
versionWidth=300px
```

The **downloadCountWidth** would let me deal with packages that have low (or high) counts. 
The **versionWidth** would let me deal with the version labels like "-preview", "-daily", and so on. 

For example, something like:
` [![BotBuilder Badge](https://buildstats.info/myget/botbuilder/botbuilder-v4-dotnet-daily/Microsoft.Bot.Builder.AI.LUIS?includePreReleases=true&downloadCountWidth=500px&versionWidth=300px)](https://botbuilder.myget.org/feed/botbuilder-v4-dotnet-daily/package/nuget/Microsoft.Bot.Builder.AI.LUIS)`

**Comment by dustinmoris** [comment]
What would you expect to happen with text which overflows the set width? Should it be simply cut off or would you prefer it to end with an ellipsis (which then would reduce even more of the version/download text)?

**Comment by cleemullins** [comment]
Personally I think the ellipse is good, as it provides a visual indicator that I need to widen it.

... but I have no data to back this up as the “right” choice.

Another option would be “min width” and if it needs to be wider, then so be it. For me, this would be fine.


________________________________

**Comment by dustinmoris** [comment]
Hi @cleemullins, sorry for the slight delay, I've just pushed a new version which supports the following two query parameters: `vWidth` and `dWidth`. Both accept an integer value which represents the pixel amount.

You can do this now:

```
https://buildstats.info/myget/botbuilder/botbuilder-v4-dotnet-daily/Microsoft.Bot.Builder.AI.LUIS?includePreReleases=true&vWidth=150&dWidth=50
```

I haven't added the ellipsis yet, but hope this addresses your current requirements enough for now.

**Comment by cleemullins** [comment]
Thanks Dustin! I just asked @godsanchez to integrate this now. : )
