### ISSUE TITLE
Question: Is it possible to provide a fixed NuGet version?

### ISSUE THREAD

**Issue by StefH** [dustinmoris/CI-BuildStats#28]
Like :
`https://buildstats.info/nuget/LinqKit.Microsoft.EntityFrameworkCore?packageVersion=1.1.16` ?

**Comment by dustinmoris** [comment]
Not possible at the moment but you can provide a PR, unfortunately I don't have time to do this myself in the distant future.

**Comment by dustinmoris** [comment]
I'm in the process of moving the service to a new Kubes cluster as part of this deployment, it is down for a bit now. Apologies but I'll let you knwo when it's done then you can test it!

**Comment by dustinmoris** [comment]
It's up now and working! The `packageVersion` query parameter works now!
