### ISSUE TITLE
NuGet badge does not seem to support packages using SemVer 2.0.0

### ISSUE THREAD

**Issue by Zastai** [dustinmoris/CI-BuildStats#31]
I tried a badge for my package: [![NuGet Badge](https://buildstats.info/nuget/MetaBrainz.MusicBrainz)](https://www.nuget.org/packages/MetaBrainz.MusicBrainz/)

At the time of writing, the current version is 2.0.1 (as of an hour ago), with 2.0.0 a month old.
However, the badge reports v1.1.3.

This may be because versions 2.0.0 and up use SemVer 2.0.0 and have build metadata included in the full name. The full version id for v2.0.0 is `2.0.0+20200322.182103.397` and that of v2.0.1 is `2.0.1+20200417.165623.692`.

**Comment by dustinmoris** [comment]
Thanks for reporting, I've added a fix and will roll this out shortly!

**Comment by Zastai** [comment]
Thanks for the speedy fix!
