### ISSUE TITLE
NuGet: allow leaving off download stats

### ISSUE THREAD

**Issue by Zastai** [dustinmoris/CI-BuildStats#32]
It is currently possible to set `dwidth` to 0, but that currently causes the badge to be rendered as two separate blocks instead of a single image: ![NuGet Badge](https://buildstats.info/nuget/MetaBrainz.MusicBrainz?dwidth=0) (it looks like the "nuget" portion of the badge also takes cues about its width from `dwidth`).

Could that rendering be fixed so that it produces a "complete" looking badge?
Alternatively, would it be possible to add a parameter to indicate that only the latest package version is needed (i.e. leave off the download count)?

**Comment by dustinmoris** [comment]
Thanks for reporting. I've just pushed a fix which I'll deploy as soon as the container is ready. I've fixed the rendering so you can set `dWidth=0` and it should render fine now.

**Comment by Zastai** [comment]
Perfect - thanks for the speedy fix.
