### ISSUE TITLE
MyGet badge broken?

### ISSUE THREAD

**Issue by StefH** [dustinmoris/CI-BuildStats#38]
When I reference a MyGet badge like:
`https://buildstats.info/myget/wiremock-net/WireMock.Net`
I get response:
`Package not found`

However this worked before and the package is present:
https://www.myget.org/feed/wiremock-net/package/nuget/WireMock.Net

?

Markdown looks like:
![image](https://user-images.githubusercontent.com/249938/88766538-79ebd200-d178-11ea-8b99-89decee2cfe5.png)

**Comment by dustinmoris** [comment]
Hi, sorry about this breaking change, but there was an issue which has been fixed so now the MyGet badges behave same and for Nuget.

You have to allow pre-release packages since your package doesn't have a stable release yet:

```
https://buildstats.info/myget/wiremock-net/WireMock.Net?includePreReleases=true
```

**Comment by StefH** [comment]
OK.

Thanks for the help.
