### ISSUE TITLE
GitHub dark mode makes titles hard to see

### ISSUE THREAD

**Issue by smorimoto** [dustinmoris/CI-BuildStats#41]
For example:
![image](https://user-images.githubusercontent.com/38746192/102177273-8930a980-3ee6-11eb-9e86-0b95053a7729.png)

**Comment by dustinmoris** [comment]
Thanks, I have to check if `currentColor` can fix that: https://hiddedevries.nl/en/blog/2018-12-24-making-single-color-svg-icons-work-in-dark-mode

**Comment by dustinmoris** [comment]
I couldn't find a way to invert the colours reliably so decided to change the title colour to something neutral which should work more or less for both themes. Let me know what you think and if there are any other labels which you suggest to change.

**Comment by smorimoto** [comment]
I'm not sure, but we might be able to do that by using `prefers-color-scheme`.

**Comment by smorimoto** [comment]
By the way, I think using blue is a reasonable idea, but it might look more natural if you use the same color as GitHub's Color System.
https://primer.style/css/support/color-system

**Comment by dustinmoris** [comment]
I think the problem with `prefers-color-scheme` is that it respects the browser setting, however GitHub's colour preference can be configured in the user's settings, which can be different than the browser's default colour scheme. For example, I have dark mode on my MacBook enabled, but have the light theme configured in my GitHub settings. Maybe I did something wrong but when I was testing locally I didn't get it working. If you have experience and can suggest how to do it then I'll try again!

Shall I use this blue then: #2188ff?

**Comment by smorimoto** [comment]
Oh, indeed. Then using blue instead is probably the best idea right now. Yes, it looks more natural, but I don't have a strong opinion about it.

**Comment by dustinmoris** [comment]
BTW just seen your sponsor! Many many thanks =)

**Comment by smorimoto** [comment]
I really like this, but at the same time I know it's not running for free...
