### ISSUE TITLE
Add documentation or support for Github Actions branches

### ISSUE THREAD

**Issue by davidkassa** [dustinmoris/CI-BuildStats#43]
This seems to work:
https://buildstats.info/github/chart/davidkassa/dvc-rofr-stats?includeBuildsFromPullRequest=false

This does not:
https://buildstats.info/github/chart/davidkassa/dvc-rofr-stats?includeBuildsFromPullRequest=false&branch=develop

Both worked with Travis CI. I'm not sure if I need to update my branch due to how Actions work, or if it's not supported.

**Comment by dustinmoris** [comment]
It looks to me this works. What did you find was wrong about the chart?

**Comment by davidkassa** [comment]
I no longer recall. I believe it was blank or mirroring the first link. Looks to be working now.
