### ISSUE TITLE
Bars plotted "backwards" with respect to time

### ISSUE THREAD

**Issue by martincostello** [dustinmoris/CI-BuildStats#5]
I've just noticed that the bars on the graph on my repo are being shown "backwards".

I would expect the graph to be chronological with the X axis being time increasing towards the right, but the latest build is the first bar instead of the last.

https://ci-buildstats.azurewebsites.net/appveyor/chart/martincostello/sqllocaldb?branch=master&includeBuildsFromPullRequest=false

[![Build History](https://ci-buildstats.azurewebsites.net/appveyor/chart/martincostello/sqllocaldb?branch=master&includeBuildsFromPullRequest=false)](https://ci.appveyor.com/project/martincostello/sqllocaldb)

Is this by design, as it seems counter-intuitive to me?

**Comment by dustinmoris** [comment]
Makes sense, will change it today!

**Comment by dustinmoris** [comment]
Should be fixed now. Let me know if you encounter any more issues! Cheers :)

**Comment by martincostello** [comment]
Great, thank you :)
