### ISSUE TITLE
HTTP 500 trying to render graph

### ISSUE THREAD

**Issue by martincostello** [dustinmoris/CI-BuildStats#6]
I'm trying to render an AppVeyor CI graph for a new repo, but I'm getting an HTTP 500 error.

[![Build History](https://ci-buildstats.azurewebsites.net/appveyor/chart/experiandataquality/swashbuckle?branch=master&includeBuildsFromPullRequest=false)](https://ci.appveyor.com/project/experiandataquality/swashbuckle)

**Comment by dustinmoris** [comment]
Fixed. Thanks again for reporting this one!

**Comment by martincostello** [comment]
Awesome, thanks!
