### ISSUE TITLE
NuGet packages name with a period

### ISSUE THREAD

**Issue by FermJacob** [dustinmoris/CI-BuildStats#7]
Hi,

I am having an issue grabbing the image for my specific package: https://www.nuget.org/packages/Faker.Data/1.0.5

When I insert https://buildstats.info/nuget/faker.data, I get a 404 error.
When I insert https://buildstats.info/nuget/faker I get my image.

The problem is, there are a lot of faker packages (including a "Faker" package) on NuGet, so I don't know why it picked mine.

**Comment by dustinmoris** [comment]
Hi Jacob,

I am not in front of my computer right now but I believe it has to do with
the "." in your package name, which the server interprets as a file
extension, because it is in the URL path.

Please try this:
https://buildstats.info/nuget/info?packageName=faker.data

**Comment by FermJacob** [comment]
Thanks for the quick response.  When I click on that link, it points to the wrong NuGet package.

**Comment by FermJacob** [comment]
Can't edit on mobile.  Looking at the code, I can type this url and get the expected response: https://api-v3search-0.nuget.org/query?q=faker.data&skip=0&take=1&prerelease=false

I cant figure out why putting in your above url doesn't point correctly.

**Comment by dustinmoris** [comment]
Hi, I looked at it closer and found the issue. Forget the URL I posted with the query parameter. You can circumvent the dot issue by appending a trailing slash:
https://buildstats.info/nuget/faker.data/

I can easily fix the issue so that the trailing slash is not required, but I am at work now, so this has to wait for tonight. Meanwhile this should work for you and the URL will always remain working like this.

**Comment by FermJacob** [comment]
Thanks Dustin, I appreciate it!

**Comment by dustinmoris** [comment]
The URL should work without a trailing slash now as well. Let me know if you encounter any other issues!

**Comment by jpbruyere** [comment]
hello, I just got the same isue with (https://buildstats.info/nuget/Crow.OpenTK). Any idea?

**Comment by dustinmoris** [comment]
Just seen that the NuGet URL has changed. I have applied the change and the service should be updated shortly.

**Comment by jpbruyere** [comment]
It's working now, thanks a lot!
