### ISSUE TITLE
error for specific nuget

### ISSUE THREAD

**Issue by SimonCropp** [dustinmoris/CI-BuildStats#8]
this gives https://buildstats.info/nuget/NServiceBus.PostgreSQL

```
BuildStats.info

Internal Error

The server encountered an internal error while processing your request.
```

but all my other ones work. Is there any more info/help i can give?

BTW keep up the awesome work

**Comment by dustinmoris** [comment]
Thanks for reporting this! Currently I filter the NuGet feed with the `prerelease=false` flag, which excludes pre-release packages. Looks like that the NServiceBus.PostgreSQL package has only pre-release versions: https://www.nuget.org/packages/NServiceBus.PostgreSQL/1.0.0-CI00021

I can extend the service to allow you to specify if you want to include or exclude pre-releases. This should be a quick change...

**Comment by SimonCropp** [comment]
@dustinmoris yeah i think that would be good. some projects stay in pre release for long periods when starting but i imagine they would still want to use build stats

**Comment by dustinmoris** [comment]
You can append the `includePreReleases=true` flag now. I used your package as the example on the readme page if that is okay? https://github.com/dustinmoris/CI-BuildStats#including-prerelease-packages

**Comment by SimonCropp** [comment]
verified :)  thanks for the amazing turn around

**Comment by dustinmoris** [comment]
Thanks for the great feedback ;)
