### ISSUE TITLE
Incorrect NuGet bagdes

### ISSUE THREAD

**Issue by sergey-tihon** [dustinmoris/CI-BuildStats#9]
For some NuGet packages badge show wrong stats
- [![NuGet Badge](https://buildstats.info/nuget/Stanford.NLP.Parser/)](https://www.nuget.org/packages/Stanford.NLP.Parser/)
- [![NuGet Badge](https://buildstats.info/nuget/Paket/)](https://www.nuget.org/packages/Paket/)

**Comment by dustinmoris** [comment]
Thanks for reporting this one. A new build is cooking and should get deployed in the next 5 mins.

**Comment by sergey-tihon** [comment]
Thanks
